SGEFront/Models/Disciplina.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace SGEFront.Models
{
    public class Disciplina
    {
        [Display(Name = "Disciplina ID")]
        public int DisciplinaId { get; set; }
        [Display(Name = "Nome da Disciplina")]
        [Required(ErrorMessage = "Esse campo é obrigatório.")]
        public string DisciplinaNome { get; set; }
        public List<DisciplinasAlunos> DisciplinasAlunos { get; set; }
        public List<DisciplinasCursos> DisciplinasCursos { get; set; }
        [Display(Name = "Nome do Professor")]
        [Required(ErrorMessage = "Esse campo é obrigatório.")]
        public int ProfessorID_FK { get; set; }       
        public virtual Professor Professor { get; set; }
    }
}

SGEFront/Controllers/DisciplinaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SGEFront.Service;
using SGEFront.Util;
using SGEFront.Models;

namespace SGEFront.Controllers
{
    public class DisciplinaController : Controller
    {
        // GET: Disciplina
      DisciplinaService disciplinaService = new DisciplinaService();
        ProfessorService professorService = new ProfessorService(); 

        [HttpGet]
        public ActionResult Index()
        {
            var disciplinas = disciplinaService.ListarDisciplinas();

            return View(disciplinas);



        }  

        // GET: Disciplina/Details/5
        public ActionResult Details(int id)
        {
            var disciplinas = disciplinaService.BuscarDisciplina(id);
            return View(disciplinas);
        }

    


        // GET: Disciplina/Create
        public ActionResult Create()
        {
            ViewBag.Professores = new SelectList(professorService.ListarProfessores(), "ProfessorId", "Nome");

        
            return View(nameof(Create));
        }

        // POST: Disciplina/Create
        [HttpPost]
        public ActionResult Create(Disciplina disciplina)
        {

            if (ModelState.IsValid)
            {
                //Efetivando o cadastro da tecnologia, utilizando o serviço de inclusão
                var disciplinaCreate = disciplinaService.IncluirDisciplina(disciplina);

                return RedirectToAction(nameof(Index));
            }

            return View(disciplina);         
            

        
        }

        // GET: Disciplina/Edit/5
        public ActionResult Edit(int id)
        {
            var disciplinatoEdit = disciplinaService.BuscarDisciplina(id);

            if (disciplinatoEdit != null)
            {
                return View(disciplinatoEdit);
            }
            return View(nameof(Index));
        }

        // POST: Disciplina/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, Disciplina disciplina)
        {
            if (ModelState.IsValid)
            {
                //Efetivando a edição da tecnologia, utilizando o serviço de edição
                var disciplinaEdit = disciplinaService.EditarDisciplina(id, disciplina);

                return RedirectToAction(nameof(Index));
            }

            return View(disciplina);
        }


        //Chamada da view Delete, para exclusão de uma tecnologia
        // GET: Disciplina/Delete/5
        public ActionResult Delete(int id)
        {
            var disciplinaDelete = disciplinaService.BuscarDisciplina(id);

            return View(disciplinaDelete);
        }

        //Excluir a tecnologia
        // POST: Tecnologia/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, Disciplina collection)
        {
            try
            {
                // Efetivando a exclusão da tecnologia, utilizando o serviço de exclusão
                var disciplinaDelete = disciplinaService.ExcluirDisciplina(id);

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

SGEFront/Views/Disciplina/Create.cshtml
@model SGEFront.Models.Disciplina

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>Disciplina</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.DisciplinaNome, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.DisciplinaNome, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.DisciplinaNome, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.ProfessorID_FK, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">

            @Html.DropDownListFor(model => model.ProfessorID_FK, (SelectList)ViewBag.Professores, "Selecione", new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.ProfessorID_FK, "", new { @class = "text-danger" })
        </div>
    </div>


    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

SGEFront/Views/Disciplina/Delete.cshtml
@model SGEFront.Models.Disciplina

@{
    ViewBag.Title = "Excluir Disciplina";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Disciplina</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.DisciplinaId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DisciplinaId)
        </dd>


        <dt>
            @Html.DisplayNameFor(model => model.DisciplinaNome)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DisciplinaNome)
        </dd>



    </dl>
</div>

<div class="form-group">
    <div class="col-md-offset-2 col-md-10">
        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <button type="submit" value="Excluir" class="btn btn-danger btn-sm">
                <span class="glyphicon glyphicon-trash" aria-hidden="true"></span>
                Excluir
            </button>
        }
    </div>
</div>
<p>
    <a href="@Url.Action("Index", "Disciplina")" class="btn btn-primary btn-xs">
        <span class="glyphicon glyphicon-arrow-left" aria-hidden="true"></span>
        Voltar
    </a>

</p>

SGEFront/Views/Disciplina/Details.cshtml
@model SGEFront.Models.Disciplina

@{
    ViewBag.Title = "Detalher da Disciplina";
}

<h2>Details</h2>

<div>
    <h4>Disciplina</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.DisciplinaId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DisciplinaId)
        </dd>


        <dt>
            @Html.DisplayNameFor(model => model.DisciplinaNome)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DisciplinaNome)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ProfessorID_FK)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProfessorID_FK)
        </dd>

    </dl>
</div>
<p>
    <a href="@Url.Action("Index", "Disciplina")" class="btn btn-primary btn-xs">
        <span class="glyphicon glyphicon-arrow-left" aria-hidden="true"></span>
        Voltar
    </a>
    <a href="@Url.Action("Edit", "Disciplina", new { id = Model.DisciplinaId })" class="btn btn-success btn-xs">
        <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
        Editar
    </a>
</p>

SGEFront/Views/Disciplina/Edit.cshtml
@model SGEFront.Models.Disciplina

@{
    ViewBag.Title = "Editar Disciplina";
}

<h2>Editar Disciplina</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Disciplina</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.DisciplinaId)



        <div class="form-group">
            @Html.LabelFor(model => model.DisciplinaNome, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DisciplinaNome, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DisciplinaNome, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ProfessorID_FK, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ProfessorID_FK, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ProfessorID_FK, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <button type="submit" value="Create" class="btn btn-success btn-sm">
                    <span class="glyphicon glyphicon-floppy-disk" aria-hidden="true"></span>
                    Salvar
                </button>
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

SGEFront/Views/Disciplina/Index.cshtml
@model IEnumerable<SGEFront.Models.Disciplina>

@{
    ViewBag.Title = "Disciplinas";
}

<br />
<h2>Disciplinas</h2>
<br />
<br />

<p>
    <a href="@Url.Action("Create", "Disciplina")" class="btn btn-success btn-xs">
        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
        Cadastrar
    </a>
</p>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.DisciplinaId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DisciplinaNome)
            </th>
            <th>Opções</th>
        </tr>
    </thead>
    <tbody>
        @if (Model.Count() > 0 && Model != null)
        {
            foreach (var item in Model)
            {

                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.DisciplinaId)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.DisciplinaNome)
                    </td>
                    <td>
                        <a href="@Url.Action("Edit", "Disciplina", new { id = item.DisciplinaId })" class="btn btn-success btn-xs">
                            <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
                            Editar
                        </a>
                        <a href="@Url.Action("Details", "Disciplina", new { id = item.DisciplinaId })" class="btn btn-default btn-xs">
                            <span class="glyphicon glyphicon-file" aria-hidden="true"></span>
                            Detalhes
                        </a>
                        <a href="@Url.Action("Delete", "Disciplina", new { id = item.DisciplinaId })" class="btn btn-danger btn-xs">
                            <span class="glyphicon glyphicon-trash" aria-hidden="true"></span>
                            Excluir
                        </a>
                    </td>
                </tr>

            }
        }

    </tbody>

</table>