SGEFront/Models/Funcionario.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using SGEFront.Enums;

namespace SGEFront.Models
{
    public class Funcionario
    {

        [Display(Name = "Funcionario Id")]
        public int FuncionarioId { get; set; }
        public string Nome { get; set; }
        public string Endereco { get; set; }
        public string Email { get; set; }
        public string Telefone { get; set; }
        public NiveldePermissaoEnum NiveldePermissaoEnum { get; set; }
    }
}

SGEFront/Controllers/FuncionarioController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SGEFront.Service;
using SGEFront.Models;
using SGEFront.Util;
namespace SGEFront.Controllers
{
    public class FuncionarioController : Controller
    {        //Serviços utilizados no controller
        FuncionarioService funcionarioService = new FuncionarioService();
        DisciplinaService disciplinaService = new DisciplinaService();


        //Buscando todos os funcionarios e retornando na view Index
        // GET: Funcionario
        public ActionResult Index()
        {
            List<Funcionario> listaFuncionarios = new List<Funcionario>();

            var funcionarios = funcionarioService.ListarFuncionarios();

            return View(funcionarios);
        }

        //Buscando o funcionarios, carregando a lista de check box e retornando para a view Details
        // GET: Funcionario/Details/5
        public ActionResult Details(int id)
        {
            var funcionario = funcionarioService.BuscarFuncionario(id);


            return View(funcionario);
        }

        //Chamada da view Create, para cadastrar novo funcionario
        // GET: Funcionario/Create
        public ActionResult Create()
        {

            //Preenchedo a ViewBag com as vagas, para carregar no dropdownlist


            Funcionario funcionario = new Funcionario();


            //Buscando todas as tecnologias cadastradas, para retornar as opções como checkbox


            return View(funcionario);
        }

        //Cadastrar o funcionario
        // POST: Funcionario/Create
        [HttpPost]
        public ActionResult Create(Funcionario funcionario)
        {


            //Efetivando o cadastro do funcionario, utilizando o serviço de inclusão
            var funcionarioCreate = funcionarioService.IncluirFuncionario(funcionario);

            return RedirectToAction(nameof(Index));



            return View(funcionario);
        }

        //Chamada da view Edit, para editar um funcionario
        // GET: Funcionario/Edit/5
        public ActionResult Edit(int id)
        {


            //Realizando a busca do funcionario, utilizando o serviço de busca
            var funcionarioEdit = funcionarioService.BuscarFuncionario(id);




            if (funcionarioEdit != null)
            {
                return View(funcionarioEdit);
            }
            return View(nameof(Index));
        }

        //Editar o funcionario
        // POST: Funcionario/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, Funcionario funcionario)
        {


            if (ModelState.IsValid)
            {
                //Efetivando a edição do funcionario, utilizando o serviço de edição
                var funcionarioEdit = funcionarioService.EditarFuncionario(id, funcionario);

                return RedirectToAction(nameof(Index));
            }

            return View(funcionario);
        }

        //Chamada da view Delete, para exclusão de um funcionario
        // GET: Funcionario/Delete/5
        public ActionResult Delete(int id)
        {
            var funcionarioDelete = funcionarioService.BuscarFuncionario(id);

            return View(funcionarioDelete);

        }

        //Excluir o funcionario
        // POST: Funcionario/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, Funcionario collection)
        {
            try
            {
                // Efetivando a exclusão do funcionario, utilizando o serviço de exclusão
                var funcionarioDelete = funcionarioService.ExcluirFuncionario(id);

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }


    }
}

SGEFront/Views/Funcionario/Create.cshtml
@model SGEFront.Models.Funcionario

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) { 

  
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <h4>Funcionario</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.Nome, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Endereco, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Endereco, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Endereco, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Telefone, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Telefone, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Telefone, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.NiveldePermissaoEnum, htmlAttributes: new { @class = "control-label col-md-2" })
                @Html.EnumDropDownListFor(model => model.NiveldePermissaoEnum);
                @Html.ValidationMessageFor(model => model.NiveldePermissaoEnum, "", new { @class = "text-danger" })
            </div>


            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create" class="btn btn-default" />
                </div>
            </div>
        </div>
    }


    <div>
        <a href="@Url.Action("Index", "Funcionario")" class="btn btn-primary btn-xs">
            <span class="glyphicon glyphicon-arrow-left" aria-hidden="true"></span>
            Voltar
        </a>
    </div>

    @section Scripts {
        @Scripts.Render("~/bundles/jqueryval")
    }

SGEFront/Views/Funcionario/Index.cshtml
@model IEnumerable<SGEFront.Models.Funcionario>

@{
    ViewBag.Title = "Funcionarios";
}

<br />
<h2>Funcionarios</h2>
<br />
<br />

<p>
    <a href="@Url.Action("Create", "Funcionario")" class="btn btn-success btn-xs">
        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
        Cadastrar
    </a>
</p>

<table class="table">
    <thead>
        <tr>
            <th>

                @Html.DisplayNameFor(model => model.FuncionarioId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Nome)
            </th>
            <th>Opções</th>
        </tr>
    </thead>
    <tbody>
        @if (Model.Count() > 0 && Model != null)
        {
            foreach (var item in Model)
            {

                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.FuncionarioId)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Nome)
                    </td>
                    <td>
                        <a href="@Url.Action("Edit", "Funcionarios", new { id = item.FuncionarioId })" class="btn btn-success btn-xs">
                            <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
                            Editar
                        </a>
                        <a href="@Url.Action("Details", "Funcionarios", new { id = item.FuncionarioId })" class="btn btn-default btn-xs">
                            <span class="glyphicon glyphicon-file" aria-hidden="true"></span>
                            Detalhes
                        </a>
                        <a href="@Url.Action("Delete", "Funcionarios", new { id = item.FuncionarioId })" class="btn btn-danger btn-xs">
                            <span class="glyphicon glyphicon-trash" aria-hidden="true"></span>
                            Excluir
                        </a>
                    </td>
                </tr>

            }
        }

    </tbody>

</table>