SGEFront/Models/Professor.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SGEFront.Enums;

namespace SGEFront.Models
{
    public class Professor
    {
       
    
        public int ProfessorId { get; set; }
        public string Nome { get; set; }
        public string Endereco { get; set; }
        public string Email { get; set; }
        public string Telefone { get; set; }
        public NiveldePermissaoEnum NiveldePermissaoEnum { get; set; }      
        
        

}
}

SGEFront/Controllers/ProfessorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SGEFront.Service;
using SGEFront.Models;
using SGEFront.Util;
namespace SGEFront.Controllers
{
    public class ProfessorController : Controller
    {        //Serviços utilizados no controller
        ProfessorService professorService = new ProfessorService();
        DisciplinaService disciplinaService = new DisciplinaService();


        //Buscando todos os professors e retornando na view Index
        // GET: Professor
        public ActionResult Index()
        {
            List<Professor> listaProfessors = new List<Professor>();

            var professors = professorService.ListarProfessores();

            return View(professors);
        }

        //Buscando o professors, carregando a lista de check box e retornando para a view Details
        // GET: Professor/Details/5
        public ActionResult Details(int id)
        {
            var professor = professorService.BuscarProfessor(id);


            return View(professor);
        }

        //Chamada da view Create, para cadastrar novo professor
        // GET: Professor/Create
        public ActionResult Create()
        {

            //Preenchedo a ViewBag com as vagas, para carregar no dropdownlist
            ViewBag.Disciplinas = new SelectList(disciplinaService.ListarDisciplinas(), "DisciplinaId", "DisciplinaNome");

            Professor professor = new Professor();


            //Buscando todas as tecnologias cadastradas, para retornar as opções como checkbox


            return View(professor);
        }

        //Cadastrar o professor
        // POST: Professor/Create
        [HttpPost]
        public ActionResult Create(Professor professor)
        {


            //Efetivando o cadastro do professor, utilizando o serviço de inclusão
            var professorCreate = professorService.IncluirProfessor(professor);

            return RedirectToAction(nameof(Index));



            return View(professor);
        }

        //Chamada da view Edit, para editar um professor
        // GET: Professor/Edit/5
        public ActionResult Edit(int id)
        {


            //Realizando a busca do professor, utilizando o serviço de busca
            var professorEdit = professorService.BuscarProfessor(id);




            if (professorEdit != null)
            {
                return View(professorEdit);
            }
            return View(nameof(Index));
        }

        //Editar o professor
        // POST: Professor/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, Professor professor)
        {


            if (ModelState.IsValid)
            {
                //Efetivando a edição do professor, utilizando o serviço de edição
                var professorEdit = professorService.EditarProfessor(id, professor);

                return RedirectToAction(nameof(Index));
            }

            return View(professor);
        }

        //Chamada da view Delete, para exclusão de um professor
        // GET: Professor/Delete/5
        public ActionResult Delete(int id)
        {
            var professorDelete = professorService.BuscarProfessor(id);                  
            
                return View(professorDelete);           
            
        }

        //Excluir o professor
        // POST: Professor/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, Professor collection)
        {
            try
            {
                // Efetivando a exclusão do professor, utilizando o serviço de exclusão
                var professorDelete = professorService.ExcluirProfessor(id);

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

  
    }
}

SGEFront/Views/Professor/Create.cshtml
@model SGEFront.Models.Professor

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm("Create", "Professor", FormMethod.Post))
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <h4>Professor</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.Nome, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Endereco, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Endereco, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Endereco, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Telefone, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Telefone, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Telefone, "", new { @class = "text-danger" })
        </div>
    </div>


    <div class="form-group">
        @Html.LabelFor(model => model.NiveldePermissaoEnum, htmlAttributes: new { @class = "control-label col-md-2" })
        @Html.EnumDropDownListFor(model => model.NiveldePermissaoEnum);
        @Html.ValidationMessageFor(model => model.NiveldePermissaoEnum, "", new { @class = "text-danger" })
    </div>



    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

SGEFront/Views/Professor/Delete.cshtml
@model SGEFront.Models.Professor

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Professor</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Nome)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nome)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Endereco)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Endereco)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Telefone)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Telefone)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

<p>
    <a href="@Url.Action("Index", "Professor")" class="btn btn-primary btn-xs">
        <span class="glyphicon glyphicon-arrow-left" aria-hidden="true"></span>
        Voltar
    </a>

</p>

SGEFront/Views/Professor/Details.cshtml
@model SGEFront.Models.Professor

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Professor</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Nome)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nome)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Endereco)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Endereco)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Telefone)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Telefone)
        </dd>

    </dl>
</div>
<p>
    <a href="@Url.Action("Index", "Professor")" class="btn btn-primary btn-xs">
        <span class="glyphicon glyphicon-arrow-left" aria-hidden="true"></span>
        Voltar
    </a>
    <a href="@Url.Action("Edit", "Professor", new { id = Model.ProfessorId })" class="btn btn-success btn-xs">
        <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
        Editar
    </a>

</p>

SGEFront/Views/Professor/Edit.cshtml
@model SGEFront.Models.Professor

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Professor</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ProfessorId)

        <div class="form-group">
            @Html.LabelFor(model => model.Nome, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Endereco, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Endereco, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Endereco, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Telefone, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Telefone, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Telefone, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

SGEFront/Views/Professor/Index.cshtml
@model IEnumerable<SGEFront.Models.Professor>

@{
    ViewBag.Title = "Professores";
}

<br />
<h2>Professores</h2>
<br />
<br />

<p>
    <a href="@Url.Action("Create", "Professor")" class="btn btn-success btn-xs">
        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
        Cadastrar
    </a>
</p>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.ProfessorId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Nome)
            </th>
            <th>Opções</th>
        </tr>
    </thead>
    <tbody>
        @if (Model.Count() > 0 && Model != null)
        {
            foreach (var item in Model)
            {

                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.ProfessorId)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Nome)
                    </td>
                    <td>
                        <a href="@Url.Action("Edit", "Professor", new { id = item.ProfessorId })" class="btn btn-success btn-xs">
                            <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
                            Editar
                        </a>
                        <a href="@Url.Action("Details", "Professor", new { id = item.ProfessorId })" class="btn btn-default btn-xs">
                            <span class="glyphicon glyphicon-file" aria-hidden="true"></span>
                            Detalhes
                        </a>
                        <a href="@Url.Action("Delete", "Professor", new { id = item.ProfessorId })" class="btn btn-danger btn-xs">
                            <span class="glyphicon glyphicon-trash" aria-hidden="true"></span>
                            Excluir
                        </a>
                    </td>
                </tr>

            }
        }

    </tbody>

</table>