SGEFront/Models/Aluno.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using SGEFront.Enums;

namespace SGEFront.Models
{
    public class Aluno
    {
        [Display(Name = "Aluno Id")]
        public int AlunoId { get; set; }
        public string Nome { get; set; }
        public string Endereco { get; set; }
        public string Email { get; set; }
        public string Telefone { get; set; }
        public NiveldePermissaoEnum NiveldePermissaoEnum { get; set; }

        public List<DisciplinasAlunos> DisciplinasAlunos { get; set; }
        public bool Status { get; set; }

        [Display(Name = "Curso")]
        [Required(ErrorMessage = "Esse campo é obrigatório.")]
        public int CursoID_FK { get; set; }       
        public virtual Curso Curso { get; set; }
        public Aluno()
        {
        }
    }
}

SGEFront/Controllers/AlunoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SGEFront.Service;
using SGEFront.Models;

namespace SGEFront.Controllers
{
    public class AlunoController : Controller
    {

        AlunoService alunoService = new AlunoService();
      
       CursoService cursoService = new CursoService();
        ProfessorService professorService = new ProfessorService();
        DisciplinaService disciplinaService = new DisciplinaService();  


        // GET: Aluno
        public ActionResult Index()
        {
            List<Aluno> listaAlunos = new List<Aluno>();

            var alunos = alunoService.ListarAlunos();

            return View(alunos);
        }


        //Buscando o alunos, carregando a lista de check box e retornando para a view Details
        // GET: Aluno/Details/5
        public ActionResult Details(int id)
        {
            var aluno = alunoService.BuscarAluno(id);


            return View(aluno);
        }

        //Chamada da view Create, para cadastrar novo aluno
        // GET: Aluno/Create
        public ActionResult Create()
        {

            //Preenchedo a ViewBag com as vagas, para carregar no dropdownlist
            ViewBag.Cursos = new SelectList(cursoService.ListarCursos(), "CursoId", "CursoNome");

            Aluno aluno = new Aluno();


            //Buscando todas as tecnologias cadastradas, para retornar as opções como checkbox


            return View(aluno);
        }

        //Cadastrar o aluno
        // POST: Aluno/Create
        [HttpPost]
        public ActionResult Create(Aluno aluno)
        {

          
            //Efetivando o cadastro do aluno, utilizando o serviço de inclusão
            var alunoCreate = alunoService.IncluirAluno(aluno);

            return RedirectToAction(nameof(Index));



            return View(aluno);
        }

        //Chamada da view Edit, para editar um aluno
        // GET: Aluno/Edit/5
        public ActionResult Edit(int id)
        {


            //Realizando a busca do aluno, utilizando o serviço de busca
            var alunoEdit = alunoService.BuscarAluno(id);




            if (alunoEdit != null)
            {
                return View(alunoEdit);
            }
            return View(nameof(Index));
        }

        //Editar o aluno
        // POST: Aluno/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, Aluno aluno)
        {


            if (ModelState.IsValid)
            {
                //Efetivando a edição do aluno, utilizando o serviço de edição
                var alunoEdit = alunoService.EditarAluno(id, aluno);

                return RedirectToAction(nameof(Index));
            }

            return View(aluno);
        }

        //Chamada da view Delete, para exclusão de um aluno
        // GET: Aluno/Delete/5
        public ActionResult Delete(int id)
        {
            var alunoDelete = alunoService.BuscarAluno(id);

            return View(alunoDelete);

        }

        //Excluir o aluno
        // POST: Aluno/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, Aluno collection)
        {
            try
            {
                // Efetivando a exclusão do aluno, utilizando o serviço de exclusão
                var alunoDelete = alunoService.ExcluirAluno(id);

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }



 

        public ActionResult CadastrarNotasAlunos(int id) {

            var aluno = alunoService.BuscarAluno(id);
            var professor=professorService.BuscarProfessor(id);
            var curso = cursoService.BuscarCurso(aluno.CursoID_FK);
            var lista = aluno.DisciplinasAlunos;
            var lista2 = curso.DisciplinasCursos;


            ViewBag.Alunos = new SelectList(alunoService.ListarAlunos().Where( o => o.CursoID_FK==aluno.Curso.CursoId), "AlunoId", "Nome");
            ViewBag.Disciplinas = new SelectList(disciplinaService.ListarDisciplinas().Where(o => lista2.Any(o2 => o2.DisciplinaID_FK == o.DisciplinaId)), "DisciplinaId", "DisciplinaNome"); ;





            return View(lista);
        }



        [HttpPost]
        public ActionResult CadastrarNotasAlunos(int id, DisciplinasAlunos disciplinasAlunos)
        {


            var aluno = alunoService.BuscarAluno(id);            
            //aluno.DisciplinasAlunos = new List<DisciplinasAlunos>();            
            

            DisciplinasAlunos disciplinaAluno = new DisciplinasAlunos();

            disciplinaAluno.AlunoID_FK = aluno.AlunoId;
            disciplinaAluno.DisciplinaID_FK = disciplinasAlunos.DisciplinaID_FK;
            disciplinaAluno.Nota1 = disciplinasAlunos.Nota1;
            disciplinaAluno.Nota2 = disciplinasAlunos.Nota2;
            disciplinaAluno.MediaFinal = ((disciplinaAluno.Nota1) + (disciplinaAluno.Nota2)) / 2;


            aluno.DisciplinasAlunos.Add(disciplinaAluno);                         




            if (ModelState.IsValid)
            {
                //Efetivando a edição da tecnologia, utilizando o serviço de edição
                var alunoEdit = alunoService.EditarAluno(id, aluno);

                return RedirectToAction(nameof(Index));
            }

            return View("Index");



        }

        [HttpGet]
        public ActionResult MostrarInfoAlunos(int id)
        {
            var buscarAluno = alunoService.BuscarAluno(id);

            for (int i = 0; i < buscarAluno.DisciplinasAlunos.Count; i++)
            {
                buscarAluno.DisciplinasAlunos[i].Aluno = new Aluno();
                buscarAluno.DisciplinasAlunos[i].Aluno.AlunoId = buscarAluno.AlunoId;
                buscarAluno.DisciplinasAlunos[i].Aluno.Nome = buscarAluno.Nome;

                i = i++;
            }


            var lista = buscarAluno.DisciplinasAlunos;

            //retorna a lista de tecnologias da vaga, para ser apresentada na view, e ter a opções de cadastro de peso.
            return View(lista);

        }
    }
}

SGEFront/Views/Aluno/CadastrarNotasAlunos.cshtml
@model  IEnumerable<SGEFront.Models.DisciplinasAlunos>
@using SGEFront.Models;
@{
    ViewBag.Title = "NotasAlunos";
}

<h2>NotasAlunos</h2>

@using (Html.BeginForm("CadastrarNotasAlunos", "Aluno", FormMethod.Post))
{
    @Html.AntiForgeryToken()
<div class="form-horizontal">
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.FirstOrDefault().Id);
    

    <div class="form-group">
        @Html.LabelFor(model => model.FirstOrDefault().Aluno.Nome, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">

            @Html.DropDownListFor(model => model.FirstOrDefault().AlunoID_FK, (SelectList)ViewBag.Alunos, "Selecione", new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.FirstOrDefault().AlunoID_FK, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.FirstOrDefault().Disciplina.DisciplinaNome, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">

            @Html.DropDownListFor(model => model.FirstOrDefault().DisciplinaID_FK, (SelectList)ViewBag.Disciplinas, "Selecione", new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.FirstOrDefault().DisciplinaID_FK, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.FirstOrDefault().Nota1, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.FirstOrDefault().Nota1, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.FirstOrDefault().Nota1, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.FirstOrDefault().Nota2, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.FirstOrDefault().Nota2, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.FirstOrDefault().Nota2, "", new { @class = "text-danger" })
        </div>
    </div>


    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Salvar" class="btn btn-default" />
        </div>
    </div>

</div>
}
<div>
    @Html.ActionLink("Voltar", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

SGEFront/Views/Aluno/Create.cshtml
@model SGEFront.Models.Aluno

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>Aluno</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.Nome, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Endereco, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Endereco, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Endereco, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Telefone, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Telefone, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Telefone, "", new { @class = "text-danger" })
        </div>
    </div>

     <div class="form-group">
        @Html.LabelFor(model => model.CursoID_FK, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
         
            @Html.DropDownListFor(model => model.CursoID_FK, (SelectList)ViewBag.Cursos, "Selecione", new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.CursoID_FK, "", new { @class = "text-danger" })
        </div>
    </div>




    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

SGEFront/Views/Aluno/Delete.cshtml
@model SGEFront.Models.Aluno

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Aluno</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Nome)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nome)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Endereco)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Endereco)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Telefone)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Telefone)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CursoID_FK)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CursoID_FK)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

<p>
    <a href="@Url.Action("Index", "Aluno")" class="btn btn-primary btn-xs">
        <span class="glyphicon glyphicon-arrow-left" aria-hidden="true"></span>
        Voltar
    </a>

</p>

SGEFront/Views/Aluno/Details.cshtml
@model SGEFront.Models.Aluno

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Aluno</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Nome)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nome)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Endereco)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Endereco)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Telefone)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Telefone)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CursoID_FK)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CursoID_FK)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.AlunoId }) |
    @Html.ActionLink("Back to List", "Index")
</p>

SGEFront/Views/Aluno/Edit.cshtml
@model SGEFront.Models.Aluno

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Aluno</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.AlunoId)

        <div class="form-group">
            @Html.LabelFor(model => model.Nome, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Endereco, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Endereco, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Endereco, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Telefone, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Telefone, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Telefone, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CursoID_FK, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CursoID_FK, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CursoID_FK, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

SGEFront/Views/Aluno/Index.cshtml
@model IEnumerable<SGEFront.Models.Aluno>

@{
    ViewBag.Title = "Alunos";
}

<br />
<h2>Alunos</h2>
<br />
<br />

<p>
    <a href="@Url.Action("Create", "Aluno")" class="btn btn-success btn-xs">
        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
        Cadastrar
    </a>
</p>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.AlunoId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Nome)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Status)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Curso.CursoNome)
            </th>
            
        </tr>
    </thead>
    <tbody>
        @if (Model.Count() > 0 && Model != null)
        {
            foreach (var item in Model)
            {

                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.AlunoId)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Nome)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Status)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Curso.CursoNome)
                    </td>

                    <td>
                        <a href="@Url.Action("Edit", "Aluno", new { id = item.AlunoId })" class="btn btn-success btn-xs">
                            <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
                            Editar
                        </a>
                        <a href="@Url.Action("Details", "Aluno", new { id = item.AlunoId })" class="btn btn-default btn-xs">
                            <span class="glyphicon glyphicon-file" aria-hidden="true"></span>
                            Detalhes
                        </a>
                        <a href="@Url.Action("Delete", "Aluno", new { id = item.AlunoId })" class="btn btn-danger btn-xs">
                            <span class="glyphicon glyphicon-trash" aria-hidden="true"></span>
                            Excluir
                        </a>

                        <a href="@Url.Action("CadastrarNotasAlunos", "Aluno", new { id = item.AlunoId })" class="btn btn-info btn-xs">
                            <span class="glyphicon glyphicon-trash" aria-hidden="true"></span>
                            Editar Notas
                        </a>
                        <a href="@Url.Action("MostrarInfoAlunos", "Aluno", new { id = item.AlunoId })" class="btn btn-primary btn-xs">
                            <span class="glyphicon glyphicon-trash" aria-hidden="true"></span>
                            Info Notas
                        </a>
                    </td>
                </tr>

            }
        }

    </tbody>

</table>

SGEFront/Views/Aluno/MostrarInfoAlunos.cshtml
@model  IEnumerable<SGEFront.Models.DisciplinasAlunos>

@{
    ViewBag.Title = "MostrarInfoAlunos";
}

<h2>MostrarInfoAlunos</h2>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Aluno.Nome)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Aluno.DisciplinasAlunos.FirstOrDefault().Disciplina.DisciplinaNome)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Aluno.DisciplinasAlunos.FirstOrDefault().MediaFinal)
            </th>
        </tr>
    </thead>
    <tbody>
        @if (Model.Count() > 0)
        {
            foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Aluno.Nome)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Disciplina.DisciplinaNome)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.MediaFinal)
                    </td>


                </tr>
            }
        }
    </tbody>

</table>